import { TrendingDown, TrendingUp } from "lucide-react";

import { receipt } from "@/lib/receipt";
import { formatWad, wadToNumber } from "@/lib/wad";
import { FieldLabel, NumericReadout } from "@/components/NumericReadout";
import { PnlChart } from "@/components/PnlChart";
import { ReceiptHeading, Reveal } from "@/components/landing-client";

export default function SimulatePage() {
  const series = receipt.series.map((s) => ({
    tick: s.tick,
    stockPnl: wadToNumber(s.stockPnlWad),
    keelPnl: wadToNumber(s.keelPnlWad),
  }));

  const stockEnd = wadToNumber(receipt.stockEndPnlWad);
  const keelEnd = wadToNumber(receipt.keelEndPnlWad);

  return (
    <main className="relative">
      <div className="grid-substrate pointer-events-none absolute inset-0 h-[400px]" />

      <div className="relative mx-auto max-w-6xl px-6 pt-28 pb-24">
        <FieldLabel>Adversarial flow · pinned parameters</FieldLabel>
        <ReceiptHeading />
        <p className="text-readout-dim mt-4 max-w-2xl text-[14px] leading-relaxed">
          Generated by a real run of <span className="font-numeric text-readout">AdversarialFlow.s.sol</span> piped
          through <span className="font-numeric text-readout">packages/sim-report</span>. Every number below came out of
          actual contract execution — none of it is hand-typed. The series parameters (40 ticks, fixed fill size, fixed
          γ/σ²/spread/bound) are pinned in the script itself, so it reproduces run to run.
        </p>

        {/* summary */}
        <div className="border-hairline mt-10 grid gap-px overflow-hidden rounded-2xl border sm:grid-cols-3">
          <SummaryCard
            label="Stock XYCSwap"
            value={formatWad(receipt.stockEndPnlWad, 4)}
            tone="short"
            icon={<TrendingDown className="h-4 w-4" />}
            note="ground down by one-sided flow"
          />
          <SummaryCard
            label="Keel"
            value={formatWad(receipt.keelEndPnlWad, 4)}
            tone="long"
            icon={<TrendingUp className="h-4 w-4" />}
            note="reservation price defended it"
          />
          <SummaryCard
            label="Improvement"
            value={`+${formatWad(receipt.pnlImprovementWad, 4)}`}
            tone="amber"
            icon={null}
            note={`over ${receipt.ticks} identical fills`}
          />
        </div>

        <Reveal>
          <div className="border-hairline bg-panel/50 mt-6 rounded-2xl border p-8">
            <PnlChart series={series} height={260} />
          </div>
        </Reveal>

        <Reveal>
          <p className="border-neutral-amber/30 bg-neutral-amber/[0.04] text-readout-dim mt-6 rounded-xl border-l-2 p-5 text-[13px] leading-relaxed">
            {receipt.headline}
          </p>
        </Reveal>

        {/* table */}
        <Reveal>
          <div className="border-hairline mt-10 overflow-hidden rounded-2xl border">
            <div className="border-hairline bg-panel-raised/60 flex items-center justify-between border-b px-5 py-3">
              <FieldLabel>Per-fill ledger</FieldLabel>
              <NumericReadout value={`${receipt.series.length} rows`} size="xs" className="text-readout-dim" />
            </div>
            <div className="max-h-[560px] overflow-auto">
              <table className="w-full border-collapse text-[13px]">
                <thead className="bg-graphite-raised/95 sticky top-0 backdrop-blur">
                  <tr className="border-hairline text-readout-dim border-b text-left">
                    <Th>Tick</Th>
                    <Th>Mid</Th>
                    <Th>Stock inv.</Th>
                    <Th align="right">Stock PnL</Th>
                    <Th>Keel inv.</Th>
                    <Th align="right">Keel PnL</Th>
                  </tr>
                </thead>
                <tbody>
                  {receipt.series.map((row) => (
                    <tr key={row.tick} className="border-hairline/40 hover:bg-panel/60 border-b transition-colors last:border-0">
                      <Td>
                        <NumericReadout value={String(row.tick).padStart(2, "0")} size="sm" className="text-readout-dim" />
                      </Td>
                      <Td>
                        <NumericReadout value={formatWad(row.midWad, 4)} size="sm" />
                      </Td>
                      <Td>
                        <NumericReadout value={formatWad(row.stockInventoryWad, 2)} size="sm" className="text-readout-dim" />
                      </Td>
                      <Td align="right">
                        <NumericReadout
                          value={formatWad(row.stockPnlWad, 4)}
                          size="sm"
                          sign={row.stockPnlWad.startsWith("-") ? "short" : "long"}
                        />
                      </Td>
                      <Td>
                        <NumericReadout value={formatWad(row.keelInventoryWad, 2)} size="sm" className="text-readout-dim" />
                      </Td>
                      <Td align="right">
                        <NumericReadout
                          value={formatWad(row.keelPnlWad, 4)}
                          size="sm"
                          sign={row.keelPnlWad.startsWith("-") ? "short" : "long"}
                        />
                      </Td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </Reveal>

        <p className="text-readout-dim mt-6 text-center text-[12px]">
          Reproduce:{" "}
          <span className="font-numeric text-readout">forge script script/AdversarialFlow.s.sol --tc AdversarialFlow</span>
        </p>
      </div>
    </main>
  );
}

function SummaryCard({
  label,
  value,
  tone,
  icon,
  note,
}: {
  label: string;
  value: string;
  tone: "long" | "short" | "amber";
  icon: React.ReactNode;
  note: string;
}) {
  const toneClass = { long: "text-long-bright", short: "text-short-bright", amber: "text-amber-bright" }[tone];
  return (
    <div className="bg-panel/50 hover:bg-panel px-6 py-5 transition-colors">
      <div className="flex items-center justify-between">
        <FieldLabel>{label}</FieldLabel>
        <span className={toneClass}>{icon}</span>
      </div>
      <div className={`font-numeric mt-2.5 text-3xl ${toneClass}`}>{value}</div>
      <div className="text-readout-dim mt-1.5 text-[11px]">{note}</div>
    </div>
  );
}

function Th({ children, align = "left" }: { children: React.ReactNode; align?: "left" | "right" }) {
  return (
    <th
      className={`font-numeric px-5 py-2.5 text-[10px] font-medium tracking-[0.14em] uppercase ${align === "right" ? "text-right" : "text-left"}`}
    >
      {children}
    </th>
  );
}

function Td({ children, align = "left" }: { children: React.ReactNode; align?: "left" | "right" }) {
  return <td className={`px-5 py-2 ${align === "right" ? "text-right" : "text-left"}`}>{children}</td>;
}
