import { TrendingDown, TrendingUp } from "lucide-react";
import { formatUnits } from "viem";

import { receipt } from "@/lib/receipt";
import { onchainDemo } from "@/lib/onchain-demo";
import { formatWad, wadToNumber } from "@/lib/wad";
import { FieldLabel, NumericReadout } from "@/components/NumericReadout";
import { PnlChart } from "@/components/PnlChart";
import { ReceiptHeading, Reveal } from "@/components/landing-client";
import { OnchainFillCurve } from "@/components/onchain-fill-curve";

export default function SimulatePage() {
  const series = receipt.series.map((s) => ({
    tick: s.tick,
    stockPnl: wadToNumber(s.stockPnlWad),
    keelPnl: wadToNumber(s.keelPnlWad),
  }));

  const stockEnd = wadToNumber(receipt.stockEndPnlWad);
  const keelEnd = wadToNumber(receipt.keelEndPnlWad);

  return (
    <main className="relative">
      <div className="grid-substrate pointer-events-none absolute inset-0 h-[400px]" />

      <div className="relative mx-auto max-w-6xl px-6 pt-28 pb-24">
        <FieldLabel>Adversarial flow · pinned parameters</FieldLabel>
        <ReceiptHeading />
        <p className="text-readout-dim mt-4 max-w-2xl text-[14px] leading-relaxed">
          Generated by a real run of <span className="font-numeric text-readout">AdversarialFlow.s.sol</span> piped
          through <span className="font-numeric text-readout">packages/sim-report</span>. Every number below came out of
          actual contract execution — none of it is hand-typed. The series parameters ({receipt.ticks} ticks, fixed
          fill size, fixed γ/σ²/spread/bound) are pinned in the script itself, so it reproduces run to run.
        </p>

        {/* summary */}
        <div className="border-hairline mt-10 grid gap-px overflow-hidden border sm:grid-cols-3">
          <SummaryCard
            label="Stock XYCSwap"
            value={formatWad(receipt.stockEndPnlWad, 4)}
            tone="short"
            icon={<TrendingDown className="h-4 w-4" />}
            note="ground down by one-sided flow"
          />
          <SummaryCard
            label="Keel"
            value={formatWad(receipt.keelEndPnlWad, 4)}
            tone="long"
            icon={<TrendingUp className="h-4 w-4" />}
            note="reservation price defended it"
          />
          <SummaryCard
            label="Improvement"
            value={`+${formatWad(receipt.pnlImprovementWad, 4)}`}
            tone="amber"
            icon={null}
            note={`over ${receipt.ticks} identical fills`}
          />
        </div>

        <Reveal>
          <div className="border-hairline bg-panel/50 mt-6 border p-8">
            <PnlChart series={series} height={260} />
          </div>
        </Reveal>

        <Reveal>
          <p className="border-neutral-amber/30 bg-neutral-amber/[0.04] text-readout-dim mt-6 border-l-2 p-5 text-[13px] leading-relaxed">
            {receipt.headline}
          </p>
        </Reveal>

        {/* table */}
        <Reveal>
          <div className="border-hairline mt-10 overflow-hidden border">
            <div className="border-hairline bg-panel-raised/60 flex items-center justify-between border-b px-5 py-3">
              <FieldLabel>Per-fill ledger</FieldLabel>
              <NumericReadout value={`${receipt.series.length} rows`} size="xs" className="text-readout-dim" />
            </div>
            <div className="max-h-[560px] overflow-auto">
              <table className="w-full border-collapse text-[13px]">
                <thead className="bg-graphite-raised/95 sticky top-0 backdrop-blur">
                  <tr className="border-hairline text-readout-dim border-b text-left">
                    <Th>Tick</Th>
                    <Th>Mid</Th>
                    <Th>Stock inv.</Th>
                    <Th align="right">Stock PnL</Th>
                    <Th>Keel inv.</Th>
                    <Th align="right">Keel PnL</Th>
                  </tr>
                </thead>
                <tbody>
                  {receipt.series.map((row) => (
                    <tr key={row.tick} className="border-hairline/40 hover:bg-panel/60 border-b transition-colors last:border-0">
                      <Td>
                        <NumericReadout value={String(row.tick).padStart(2, "0")} size="sm" className="text-readout-dim" />
                      </Td>
                      <Td>
                        {/* 10dp, not 4: this pair's mid runs ~2.9e-4 down to
                            ~8.3e-5, so 4 decimals renders every row in the
                            table as "0.0002" or "0.0000". Matches the
                            precision packages/sim-report uses for prices. */}
                        <NumericReadout value={formatWad(row.midWad, 10)} size="sm" />
                      </Td>
                      <Td>
                        <NumericReadout value={formatWad(row.stockInventoryWad, 2)} size="sm" className="text-readout-dim" />
                      </Td>
                      <Td align="right">
                        <NumericReadout
                          value={formatWad(row.stockPnlWad, 4)}
                          size="sm"
                          sign={row.stockPnlWad.startsWith("-") ? "short" : "long"}
                        />
                      </Td>
                      <Td>
                        <NumericReadout value={formatWad(row.keelInventoryWad, 2)} size="sm" className="text-readout-dim" />
                      </Td>
                      <Td align="right">
                        <NumericReadout
                          value={formatWad(row.keelPnlWad, 4)}
                          size="sm"
                          sign={row.keelPnlWad.startsWith("-") ? "short" : "long"}
                        />
                      </Td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </Reveal>

        {/* everything above this line is the LOCAL forge simulation; everything
            below is a real chain. Kept visually separate on purpose. */}
        <Reveal>
          <div className="border-hairline mt-20 border-t pt-16">
            <FieldLabel>Not a simulation · live Base Sepolia</FieldLabel>
            <h2 className="mt-3 max-w-2xl text-2xl font-display font-normal">
              The same mechanism, off the simulator and on a chain.
            </h2>
            <p className="text-readout-dim mt-4 max-w-2xl text-[14px] leading-relaxed">
              Everything above came out of{" "}
              <span className="font-numeric text-readout">AdversarialFlow.s.sol</span> running locally against a forge
              VM — real contract execution, but a local one, which produces no transactions. Below is a separate,
              smaller run: a Keel strategy actually shipped to Base Sepolia on the real{" "}
              <span className="font-numeric text-readout">
                {onchainDemo.tokenSymbols.token0}/{onchainDemo.tokenSymbols.token1}
              </span>{" "}
              pair and hit with {onchainDemo.fills.length} real fills, each a confirmable transaction. Different run,
              different parameters, different scale — shown side by side because a local receipt and a public one prove
              different things.
            </p>
            <div className="mt-8">
              <OnchainFillCurve variant="compact" />
            </div>

            {/* The transactions themselves. Deliberately its own table rather
                than a column on the per-fill ledger above: that ledger is the
                local simulation, whose rows have no transactions at all, so a
                hash column there would be empty or invented. */}
            <div className="border-hairline mt-8 border">
              <div className="border-hairline/70 flex flex-wrap items-center justify-between gap-3 border-b px-5 py-3">
                <FieldLabel>Every fill, on chain</FieldLabel>
                <NumericReadout
                  value={`${onchainDemo.fills.length} transactions`}
                  size="xs"
                  className="text-readout-dim"
                />
              </div>
              <div className="overflow-x-auto">
                <table className="w-full border-collapse text-[13px]">
                  <thead className="bg-panel-raised/60">
                    <tr className="border-hairline text-readout-dim border-b text-left">
                      <Th>Tick</Th>
                      <Th>Inventory before</Th>
                      <Th align="right">{onchainDemo.tokenSymbols.token1} out</Th>
                      <Th align="right">Transaction</Th>
                    </tr>
                  </thead>
                  <tbody>
                    {onchainDemo.fills.map((f) => (
                      <tr
                        key={f.txHash}
                        className="border-hairline/40 hover:bg-panel/60 border-b transition-colors last:border-0"
                      >
                        <td className="px-5 py-2">
                          <NumericReadout
                            value={String(f.tick).padStart(2, "0")}
                            size="sm"
                            className="text-readout-dim"
                          />
                        </td>
                        <td className="px-5 py-2">
                          <NumericReadout
                            value={`${formatWad(f.balance0Before, 2)} ${onchainDemo.tokenSymbols.token0}`}
                            size="sm"
                          />
                        </td>
                        <td className="px-5 py-2 text-right">
                          <NumericReadout value={formatWad(f.actualAmountOut, 8)} size="sm" sign="short" />
                        </td>
                        <td className="px-5 py-2 text-right">
                          <a
                            href={`${onchainDemo.explorer}/tx/${f.txHash}`}
                            target="_blank"
                            rel="noreferrer"
                            className="font-numeric text-amber-bright text-[12px] hover:underline"
                          >
                            {f.txHash.slice(0, 10)}… ↗
                          </a>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="border-hairline/70 text-readout-dim border-t px-5 py-3 text-[11px] leading-relaxed">
                {onchainDemo.tokenSymbols.token1} paid out falls with every fill — each one pushes inventory further
                from target, so the next is priced worse for the taker. That monotonic fall is the skew, measured
                rather than modelled. Ship tx{" "}
                <a
                  href={`${onchainDemo.explorer}/tx/${onchainDemo.shipTxHash}`}
                  target="_blank"
                  rel="noreferrer"
                  className="font-numeric text-amber-bright hover:underline"
                >
                  {onchainDemo.shipTxHash.slice(0, 10)}… ↗
                </a>
              </p>
              {/* Deliberately a footnote and not a row: this fill runs the
                  other way, so "Inventory before / WETH out" would describe
                  it wrongly. It is also the one the previous router could
                  never settle, which is why it is worth naming at all. */}
              <p className="border-hairline/70 text-readout-dim border-t px-5 py-3 text-[11px] leading-relaxed">
                <span className="text-long-bright">And one covered-side fill</span> — the other direction,{" "}
                <span className="font-numeric text-readout">
                  {formatUnits(BigInt(onchainDemo.coveredFill.amountInWeth), 18)} {onchainDemo.tokenSymbols.token1}
                </span>{" "}
                in for{" "}
                <span className="font-numeric text-readout">
                  {formatUnits(BigInt(onchainDemo.coveredFill.actualAmountOutRaw), 6)}{" "}
                  {onchainDemo.tokenSymbols.token0}
                </span>{" "}
                out, bringing inventory back toward target instead of pushing it away. Its units are reversed, so it
                sits here rather than in the table above. This is the first covered fill the project has landed on
                chain: on the previous router the direction was mispriced and reverted at any realistic size.{" "}
                <a
                  href={`${onchainDemo.explorer}/tx/${onchainDemo.coveredFill.txHash}`}
                  target="_blank"
                  rel="noreferrer"
                  className="font-numeric text-amber-bright hover:underline"
                >
                  {onchainDemo.coveredFill.txHash.slice(0, 10)}… ↗
                </a>
              </p>
            </div>
          </div>
        </Reveal>

        <p className="text-readout-dim mt-10 text-center text-[12px]">
          Reproduce:{" "}
          <span className="font-numeric text-readout">forge script script/AdversarialFlow.s.sol --tc AdversarialFlow</span>
        </p>
      </div>
    </main>
  );
}

function SummaryCard({
  label,
  value,
  tone,
  icon,
  note,
}: {
  label: string;
  value: string;
  tone: "long" | "short" | "amber";
  icon: React.ReactNode;
  note: string;
}) {
  const toneClass = { long: "text-long-bright", short: "text-short-bright", amber: "text-amber-bright" }[tone];
  return (
    <div className="bg-panel/50 hover:bg-panel px-6 py-5 transition-colors">
      <div className="flex items-center justify-between">
        <FieldLabel>{label}</FieldLabel>
        <span className={toneClass}>{icon}</span>
      </div>
      <div className={`font-numeric mt-2.5 text-3xl ${toneClass}`}>{value}</div>
      <div className="text-readout-dim mt-1.5 text-[11px]">{note}</div>
    </div>
  );
}

function Th({ children, align = "left" }: { children: React.ReactNode; align?: "left" | "right" }) {
  return (
    <th
      className={`font-numeric px-5 py-2.5 text-[10px] font-medium tracking-[0.14em] uppercase ${align === "right" ? "text-right" : "text-left"}`}
    >
      {children}
    </th>
  );
}

function Td({ children, align = "left" }: { children: React.ReactNode; align?: "left" | "right" }) {
  return <td className={`px-5 py-2 ${align === "right" ? "text-right" : "text-left"}`}>{children}</td>;
}
