import receiptData from "@/data/receipt.json";

/**
 * Static fixture, generated by a real run of
 * contracts/script/AdversarialFlow.s.sol piped through
 * packages/sim-report -- not a live feed, and not hand-typed either. See
 * README.md's Demo section for the exact regeneration command; re-run it
 * before a demo if the numbers need to reflect code changes since this was
 * captured.
 */
export const receipt = receiptData as {
  ticks: number;
  startMidWad: string;
  endMidWad: string;
  trendPct: string;
  startInventoryWad: string;
  stockEndInventoryWad: string;
  keelEndInventoryWad: string;
  stockEndPnlWad: string;
  keelEndPnlWad: string;
  pnlImprovementWad: string;
  headline: string;
  series: {
    tick: number;
    midWad: string;
    stockInventoryWad: string;
    stockPnlWad: string;
    keelInventoryWad: string;
    keelPnlWad: string;
  }[];
};
